connector.name=iceberg

iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.catalog-name=demo
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://host.docker.internal:55432/demo_db
iceberg.jdbc-catalog.connection-user=admin
iceberg.jdbc-catalog.connection-password=admin
iceberg.jdbc-catalog.default-warehouse-dir=s3://demo-iceberg-warehouse/

fs.native-s3.enabled=true
s3.endpoint=http://host.docker.internal:9000
s3.region=us-east-1
s3.path-style-access=true
s3.aws-access-key=admin
s3.aws-secret-key=admin123
